// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS3Ti-Wbicfo20EeUUHCfOnHK1Ql1ff8Y',
    appId: '1:403291467562:web:0c8ac8c530d2b73d747853',
    messagingSenderId: '403291467562',
    projectId: 'example-flutter3',
    authDomain: 'example-flutter3.firebaseapp.com',
    storageBucket: 'example-flutter3.firebasestorage.app',
    measurementId: 'G-FE5QJLVE6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZkYY5ei5VNXJfntGVrevsKCVvMZJ_WRU',
    appId: '1:403291467562:android:604ace3b9bf4ea4b747853',
    messagingSenderId: '403291467562',
    projectId: 'example-flutter3',
    storageBucket: 'example-flutter3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wHBdq02vGuNygy9ET9iYyY1ewVSqSKE',
    appId: '1:403291467562:ios:9bfed19caa6346a9747853',
    messagingSenderId: '403291467562',
    projectId: 'example-flutter3',
    storageBucket: 'example-flutter3.firebasestorage.app',
    iosBundleId: 'com.example.flutter3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5wHBdq02vGuNygy9ET9iYyY1ewVSqSKE',
    appId: '1:403291467562:ios:9bfed19caa6346a9747853',
    messagingSenderId: '403291467562',
    projectId: 'example-flutter3',
    storageBucket: 'example-flutter3.firebasestorage.app',
    iosBundleId: 'com.example.flutter3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS3Ti-Wbicfo20EeUUHCfOnHK1Ql1ff8Y',
    appId: '1:403291467562:web:6f38817145d42af6747853',
    messagingSenderId: '403291467562',
    projectId: 'example-flutter3',
    authDomain: 'example-flutter3.firebaseapp.com',
    storageBucket: 'example-flutter3.firebasestorage.app',
    measurementId: 'G-91XSW5JLVV',
  );
}
